# docker-compose.yml
version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: lol_decay_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_change_me}
      MYSQL_DATABASE: ${DB_NAME:-lol_decay_tracker}
      MYSQL_USER: ${DB_USER:-lol_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-lol_password_change_me}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - lol_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: lol_decay_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${DB_USER:-lol_user}
      PMA_PASSWORD: ${DB_PASSWORD:-lol_password_change_me}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_change_me}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - lol_network

volumes:
  mariadb_data:
    driver: local

networks:
  lol_network:
    driver: bridge
